### ISSUE TITLE
[Addon Developer Support Request] - Can volumes be used in the /conf/*.yml files?

### ISSUE THREAD

**Issue by frederickjh** [docksal/addons#30]
Hi!
I submitted the adminer addon to this repo. I realized the other day that the default PHP 2M limit on uploads maximum size does not allow for many database files to be imported as they are too big.

I found that  for the adminer docker image, this PHP limit can be increased by using a **volume** to place a file in the `/usr/local/etc/php/conf.d/` directory. ([increase → Unable to upload a file. Maximum allowed file size is 2MB.](https://github.com/TimWolla/docker-adminer/issues/17#issuecomment-346016456))

In the `adminer/conf` folder I created a `uploads.ini` and then used the following in adminer.yml file:
```
  # Adminer
  adminer:
    hostname: adminer
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db # db is the default database container
      - ADMINER_PLUGINS=tables-filter tinymce # To load Adminer plugins
      - ADMINER_DESIGN=price # To use a bundled Adminer design
    labels:
      - io.docksal.virtual-host=adminer.${VIRTUAL_HOST}
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
```
`uploads.ini`
```
upload_max_filesize = 500M
post_max_size = 500M
memory_limit = -1
max_execution_time = 0
```
When I go into the running terminal with `sh` and do `ls /usr/local/etc/php/conf.d/` the file `uploads.in` is not listed and the new PHP settings in the file are not used. Running `fin logs adminer` does not show any errors.

So, is it possible to have volumes in the addons **.yml** files? Or am I missing something very obvious that I am doing incorrectly?

Thanks for your time and help!
Frederick
