### ISSUE TITLE
Coder addon with LetsEncrypt on Ubuntu server

### ISSUE THREAD

**Issue by acondura** [docksal/addons#45]
I've just finished creating an addon named 'coder' which uses a fork of https://github.com/cdr/code-server and because I'm using a wildcard SSL from LetsEncrypt on a Ubuntu server, I use URLs like ide-project1.domain.com, ide-project2.domain.com, etc.

After going through the Docksal docs for a few days now, I ran out of options to test and make http://ide-project1.domain.com go to HTTPS://ide-project1.domain.com. I looked at https://docs.docksal.io/service/web/settings/ and applied those settings but it just would not work.

HTTPS://ide-project1.domain.com does work but it does not force http to https. Any idea why?

fin config:

```
---------------------
COMPOSE_PROJECT_NAME_SAFE: joccom
COMPOSE_FILE:
/home/joccom/.docksal/stacks/volumes-bind.yml
/home/joccom/.docksal/stacks/stack-acquia.yml
/home/joccom/project/joccom/.docksal/docksal.yml
ENV_FILE:
/home/joccom/project/joccom/.docksal/docksal.env
/home/joccom/project/joccom/.docksal/docksal-local.env

PROJECT_ROOT: /home/joccom/project/joccom
DOCROOT: docroot
VIRTUAL_HOST: joccom.opncld.com
VIRTUAL_HOST_ALIASES: *.joccom.opncld.com
IP: 192.168.64.100
MYSQL: 192.168.64.100:32771

Docker Compose configuration
---------------------
services:
  cli:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      BLACKFIRE_CLIENT_ID: null
      BLACKFIRE_CLIENT_TOKEN: null
      DOCROOT: docroot
      DRUSH_ALLOW_XDEBUG: '0'
      GIT_USER_EMAIL: andrei@condurachi.ro
      GIT_USER_NAME: Andrei Condurachi
      HOST_GID: '1001'
      HOST_UID: '1001'
      PHP_IDE_CONFIG: serverName=joccom.opncld.com
      SECRET_ACAPI_EMAIL: andre*****hi.ro
      SECRET_ACAPI_KEY: zwjBt*****KjSAB
      SECRET_PLATFORMSH_CLI_TOKEN: null
      SECRET_SSH_PRIVATE_KEY: null
      SECRET_TERMINUS_TOKEN: null
      VIRTUAL_HOST: joccom.opncld.com
      XDEBUG_CONFIG: remote_connect_back=0 remote_host=192.168.64.1
      XDEBUG_ENABLED: '0'
    hostname: cli
    image: docksal/cli:php7.1
    volumes:
    - docksal_ssh_agent:/.ssh-agent:ro
    - cli_home:/home/docker:rw
    - project_root:/var/www:rw,nocopy
  coder:
    command: code-server --cert /home/coder/certs/ide-joccom.opncld.com.crt --cert-key
      /home/coder/certs/ide-joccom.opncld.com.key --allow-http -e /home/coder/.local/share/code-server/extensions
    hostname: ide-joccom
    image: acondura/code-server
    labels:
      io.docksal.virtual-host: ide-joccom.opncld.com
    user: 1000:1000
    volumes:
    - /home/joccom/.ssh:/home/coder/.ssh:rw
    - /home/joccom/.docksal/certs:/home/coder/certs:rw
    - /home/joccom/project/joccom:/home/coder/project:rw
  db:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_DATABASE: default
      MYSQL_INITDB_SKIP_TZINFO: null
      MYSQL_ONETIME_PASSWORD: null
      MYSQL_PASSWORD: user
      MYSQL_RANDOM_ROOT_PASSWORD: null
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
    hostname: db
    image: docksal/mysql:5.6-1.4
    ports:
    - 0:3306/tcp
    volumes:
    - db_data:/var/lib/mysql:rw
    - project_root:/var/www:ro,nocopy
  memcached:
    command:
    - -m
    - '128'
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: memcached
    image: memcached:1.4-alpine
  solr:
    dns:
    - 192.168.64.100
    - 8.8.8.8
    hostname: solr
    image: docksal/solr:1.0-solr4
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: solr.joccom.opncld.com,solr.joccom.opncld.com.*
      io.docksal.virtual-port: '8983'
    volumes:
    - project_root:/var/www:ro,nocopy
  varnish:
    depends_on:
      web:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      VARNISH_BACKEND_HOST: web
    hostname: varnish
    image: docksal/varnish:4.1-2.0
    labels:
      io.docksal.cert-name: none
      io.docksal.virtual-host: varnish.joccom.opncld.com,varnish.joccom.opncld.com.*
    volumes:
    - project_root:/var/www:ro,nocopy
  web:
    depends_on:
      cli:
        condition: service_started
    dns:
    - 192.168.64.100
    - 8.8.8.8
    environment:
      APACHE_BASIC_AUTH_PASS: null
      APACHE_BASIC_AUTH_USER: null
      APACHE_DOCUMENTROOT: /var/www/docroot
      APACHE_FCGI_HOST_PORT: cli:9000
    hostname: web
    image: docksal/apache:2.4-2.3
    labels:
      io.docksal.cert-name: none
      io.docksal.permanent: "true"
      io.docksal.project-root: /home/joccom/project/joccom
      io.docksal.virtual-host: joccom.opncld.com,*.joccom.opncld.com,joccom.opncld.com.*
    volumes:
    - project_root:/var/www:ro,nocopy
version: '2.1'
volumes:
  cli_home: {}
  db_data: {}
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: /home/joccom/project/joccom
      o: bind
      type: none

---------------------
```
