### ISSUE TITLE
Consider switching to Mailpit for mail service

### ISSUE THREAD

**Issue by jacobsaw** [docksal/addons#93]
Per https://github.com/mailhog/MailHog/issues/442, it appears that mailhog is basically abandoned.

We have been using https://github.com/axllent/mailpit with the mail service configuration and the image overridden and, so far, it seems to work great. Brings in some long-desired features such as bcc support.

**Comment by shelane** [comment]
A quick work around to use this would be to add `MAILHOG_IMAGE='axllent/mailpit:v1.15.1'` to your `docksal.env` file and have this in your `docksal.yml` file:
```
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
```
